### ISSUE TITLE
Metadata type changed from `list` to `tuple` affecting modification via interceptor

### ISSUE THREAD

**Issue by ohmayr** [googleapis/python-api-core#660]
The following change https://github.com/googleapis/python-api-core/commit/d96eb5cdd8120bfec97d62b09512c6fecc325be8 introduces a breaking change by changing the type of metadata from a list to a tuple resulting in users to not be able to modify the metadata via an interceptor.

The following showcase [tests](https://github.com/googleapis/gapic-generator-python/blob/main/tests/system/test_grpc_interceptor_streams.py) in the generator break, since the interceptor can no longer modify the metadata (or assign it a new value) via this function:

```python3
def _add_metadata(self, client_call_details):
        if client_call_details.metadata is not None:
            client_call_details.metadata.append((self._key, self._value))

```

**Comment by daniel-sanche** [comment]
So it looks like there are two ways to address this: 
- replace the tuple with a list in [gapic_v1.method](https://github.com/googleapis/python-api-core/blob/d96eb5cdd8120bfec97d62b09512c6fecc325be8/google/api_core/gapic_v1/method.py#L96)
- update that [_add_metadata](https://github.com/googleapis/gapic-generator-python/blob/44e9b30aac859885886a8ec61ca943a20d4f81b9/tests/system/conftest.py#L197) call to something like:
```
def _add_metadata(self, client_call_details):
        if client_call_details.metadata is not None:
            client_call_details.metadata = [(self._key, self._value), *client_call_details.metadata]
```

The type annotations for metadata seem to [only guarantee a Sequence](https://github.com/googleapis/python-api-core/blob/d96eb5cdd8120bfec97d62b09512c6fecc325be8/google/api_core/gapic_v1/method.py#L60) for metadata passed in, and [doesn't explicitly say anything](https://github.com/googleapis/python-api-core/blob/d96eb5cdd8120bfec97d62b09512c6fecc325be8/google/api_core/gapic_v1/method.py#L197) about what format the metadata will have when passed to the callable. IMO, I'd say that the bug is in the tests, which probably shouldn't be assuming a specific sequence type, and should assume metadata output will have the same structure as the input

But if we find other places are assuming a list and it's causing issues, we can always revert back to a list and change the API contract to be a list to be more specific here

**Comment by parthea** [comment]
I'm going to revert #527 as it's blocking our release for supporting protobuf 5.x . Please open a new PR to restore the feature with the suggested fix from https://github.com/googleapis/python-api-core/issues/660#issuecomment-2130285343

**Comment by parthea** [comment]
Bumping to P2 as #527 will be reverted in main

**Comment by parthea** [comment]
Closing as obsolete as the issue no longer exists in the main branch
